import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Spotlight } from "@/app/components/ui/Spotlight";
import { SparklesCore } from "./components/ui/sparkles";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Spotlight
        className="-top-40 left-0 md:left-80 md:-top-20"
        fill="white"
      />
      <body>
        
        <main className={inter.className}>{children}
        
        </main>
      </body>
    </html>
  );
}
